---
vpc_name: aap_containerized_deployment
vpc_cidr: 172.16.3.0/24
region: us-west-1
user_name: mickey.mouse
ec2_ansible_group: "{{ user_name }}"
ec2_security_group_name: "{{ vpc_name }}_SECGRP"
ec2_vpc_subnet_name: "{{ vpc_name }}_Subnet"
ec2_rt_name: "{{ vpc_name }}_RT_Internet"
ec2_igw_name: "{{ vpc_name }}_IGW"
my_email_address: "{{ user_name }}@redhat.com"
